### ISSUE TITLE
TypeError: connectionManager.has is not a function

### ISSUE THREAD

**Issue by booradleys** [pleerock/typedi#30]
Hi there, 
After calling localhost:4001/, i get this error in my console:

C:\Applications\Node\exotica\server>node app.js
Server is up and running at port 3000
TypeError: connectionManager.has is not a function
    at Object.value (C:\Applications\Node\exotica\node_modules\typeorm-typedi-extensions\decorators\OrmCustomRepository.js:13:40)
    at C:\Applications\Node\exotica\node_modules\typedi\Container.js:171:32
    at Array.forEach (native)
    at Function.Container.applyPropertyHandlers (C:\Applications\Node\exotica\node_modules\typedi\Container.js:162:23)
    at Function.Container.get (C:\Applications\Node\exotica\node_modules\typedi\Container.js:68:14)
    at C:\Applications\Node\exotica\node_modules\typedi\Container.js:148:34
    at Array.map (native)
    at Function.Container.initializeParams (C:\Applications\Node\exotica\node_modules\typedi\Container.js:143:27)
    at Function.Container.get (C:\Applications\Node\exotica\node_modules\typedi\Container.js:48:48)
    at Object.getFromContainer (C:\Applications\Node\exotica\node_modules\routing-controllers\container.js:36:42)

**Comment by pleerock** [comment]
very descriptive issue. Please open a new issue with small code samples to reproduce your issue and with proper format.
